In [4]:
import pandas as pd

# Sample DataFrame
data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [32, 75, 30, 77]
}
df = pd.DataFrame(data)
# Creating a pivot table
pivot_df = df.pivot_table(index='Date', columns='City', values='Temperature')
print(pivot_df)


City        Los Angeles  New York
Date                             
2023-01-01         75.0      32.0
2023-01-02         77.0      30.0


In [5]:
# Example 2: Pivot Table with Multiple Aggregation Functions
import pandas as pd

# Sample DataFrame
data = {
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 250],
    'Quantity': [1, 2, 3, 4]
}
df = pd.DataFrame(data)

# Creating a pivot table with multiple aggregation functions
pivot_df = df.pivot_table(index='Product', values=['Sales', 'Quantity'], aggfunc={'Sales': 'sum', 'Quantity': 'mean'})
print(pivot_df)


         Quantity  Sales
Product                 
A             2.0    300
B             3.0    400


In [6]:
#Example 3: Pivot Table with Multiple Indexes
import pandas as pd

# Sample DataFrame
data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [32, 75, 30, 77],
    'Humidity': [80, 10, 85, 5]
}
df = pd.DataFrame(data)

# Creating a pivot table with multiple indexes
pivot_df = df.pivot_table(index=['Date', 'City'], values=['Temperature', 'Humidity'])
print(pivot_df)


                        Humidity  Temperature
Date       City                              
2023-01-01 Los Angeles      10.0         75.0
           New York         80.0         32.0
2023-01-02 Los Angeles       5.0         77.0
           New York         85.0         30.0


## Np where

In [9]:
# Basic Use
import numpy as np

a = np.array([1, 2, 3, 4, 5])
result = np.where(a > 3)
print(a)
print(result)  # Output: (array([3, 4]),)


[1 2 3 4 5]
(array([3, 4]),)


In [8]:
# Replacing Values
import numpy as np

a = np.array([1, 2, 3, 4, 5])
result = np.where(a > 3, a, -1)
print(a)
print(result)  # Output: [-1 -1 -1  4  5]


[1 2 3 4 5]
[-1 -1 -1  4  5]


In [10]:
# Using with 2D Arrays
import numpy as np

a = np.array([[1, 2], [3, 4]])
result = np.where(a > 2, a, 0)
print(a)
print(result)  # Output: [[0 0] [3 4]]


[[1 2]
 [3 4]]
[[0 0]
 [3 4]]


In [11]:
# Multiple Conditions
import numpy as np

a = np.array([1, 2, 3, 4, 5])
result = np.where((a > 2) & (a < 5), a, 0)
print(a)
print(result)  # Output: [0 0 3 4 0]


[1 2 3 4 5]
[0 0 3 4 0]
